FIREWORK: 200 # name effect, price effect
WATER: 225
EXPLOSION: 200
SMOKE: 150
HEART: 300
SLIME: 150
NOTE: 200
PORTAL: 200
SPELL: 225
CLOUD: 200
SNOW: 150
LAVA: 225
FLAME: 300
VILLAGER_HAPPY: 300
MAGIC: 300
SPELL_WITCH: 300
